name: ccache-with-R
description: Sets up ccache for use with R

inputs:
  cachefile:
    description: |
      Name of the cache file. Use '\$\{\{ github.repository \}\} on call.
    required: false
    default: 'ccache_file'

runs:
  using: "composite"
  steps:
    ## Set up ccache
    - name: Get ccache
      uses: hendrikmuhs/ccache-action@v1.2.23
      with:
        key: ${{ inputs.cachefile }}
        restore-keys: ${{ inputs.cachefile }}
        append-timestamp: true
        variant: ccache
        max-size: 10G # Github has a 10GB repo cache limit

    - name: Configure ccache for R
      shell: bash
      run: bash "${{ github.action_path }}/ccache_setup.sh"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Show ccache config
      shell: bash
      run: ccache --show-config
        
    - name: Zero ccache stats
      shell: bash
      run: ccache --zero-stats
