name: ccache-with-R
description: Sets up ccache for use with R

inputs:
  key:
    description: |
      Name of the cache file key. Use e.g. '\$\{\{ github.repository \}\}
      (or parts of your matrix) on call.
    required: false
    default: 'ccache_file'
  R:
    description: |
      Whether or not to setup ~/.R/Makevars for use of R with ccache
    required: false
    default: 'TRUE'

runs:
  using: "composite"
  steps:
    ## Set up ccache
    - name: Get ccache
      uses: hendrikmuhs/ccache-action@v1.2.23
      with:
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.key }}
        ## The following three settings are re-stating their defaults for clarity
        append-timestamp: true 
        variant: ccache
        max-size: 10G # Github has a 10GB repo cache limit

    - name: Configure ccache
      shell: bash
      run: bash "${{ github.action_path }}/ccache_setup.sh"

    - name: Configure R
      shell: bash
      if: inputs.R == 'TRUE'
      run: bash "${{ github.action_path }}/r_makevars_setup.sh"
      
    - name: Show ccache config
      shell: bash
      run: ccache --show-config
        
    - name: Zero ccache stats
      shell: bash
      run: ccache --zero-stats
